name: Issue metadata

on:
  issues:
    types:
      - opened
      - edited
      - typed
      - untyped
      - field_added
      - field_removed
      - labeled
      - unlabeled

jobs:
  validate:
    uses: modwire/modwire-architecture/.github/workflows/issue-metadata.yml@main
